var d = new Date()
console.log(" ")
console.log(d.toDateString())
console.log(d.toTimeString())
console.log(d.toLocaleDateString())
console.log(d.getDate())
console.log(d.getMonth()+1)
console.log(d.getFullYear())
console.log(" ")