//console.log("___________")
console.log("Class - 7")
console.log("I am ready for my work")
console.log("It is yor lucky One " + 6)
console.log(9+9)
console.log('8' + 7)
console.log('Done Its working')
//console.log("_______________")